"""added models

Revision ID: dc76711802fd
Revises: 6c845ea1bbca
Create Date: 2025-08-14 22:40:39.501825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc76711802fd'
down_revision: Union[str, Sequence[str], None] = '6c845ea1bbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id'),
    schema='telegram_bot'
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_bot.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_code', 'item_id', name='uq_user_category_item'),
    schema='telegram_bot'
    )
    op.create_index(op.f('ix_telegram_bot_user_preferences_category_code'), 'user_preferences', ['category_code'], unique=False, schema='telegram_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_bot_user_preferences_category_code'), table_name='user_preferences', schema='telegram_bot')
    op.drop_table('user_preferences', schema='telegram_bot')
    op.drop_table('users', schema='telegram_bot')
    # ### end Alembic commands ###
