"""added last activity

Revision ID: c224aff40fe0
Revises: dc76711802fd
Create Date: 2025-10-05 08:00:19.406819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c224aff40fe0'
down_revision: Union[str, Sequence[str], None] = 'dc76711802fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True), schema='telegram_bot')
    op.execute("UPDATE telegram_bot.users SET last_active_at = created_at")
    op.alter_column('users', 'last_active_at', nullable=False, schema='telegram_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at', schema='telegram_bot')
    # ### end Alembic commands ###
