name: ${ENV_PROJECT_NAME:-syncit}

x-service-common: &service-common
  image: "" # Для dev разработки не нужен image
  volumes:
    - ${MAIN_COMPOSE_PROJECT_ROOT:-../..}/services:/app/services
    - ${MAIN_COMPOSE_PROJECT_ROOT:-../..}/libs:/app/libs

x-build-common: &build-common
  context: ../..
  target: ${ENV_MODE:-production}

services:
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"

  pgbouncer:
    ports:
      - "${PGBOUNCER_PORT:-6432}:${PGBOUNCER_PORT:-6432}"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

  api-gateway:
    build:
      dockerfile: infra/docker/api-gateway/Dockerfile
      <<: *build-common
    <<: *service-common

  gpt-api:
    build:
      dockerfile: infra/docker/gpt-api/Dockerfile
      <<: *build-common
    ports:
      - "${GPT_API_PORT:-8001}:${ENV_SERVICE_INTERNAL_PORT:-8000}"
    <<: *service-common

  scraper-api:
    build:
      dockerfile: infra/docker/scraper-api/Dockerfile
      <<: *build-common
    ports:
      - "${SCRAPER_API_PORT:-8002}:${ENV_SERVICE_INTERNAL_PORT:-8000}"
    <<: *service-common

  vacancy-parser:
    build:
      dockerfile: infra/docker/vacancy-parser/Dockerfile
      <<: *build-common
    ports:
      - "${VACANCY_PARSER_PORT:-8003}:${ENV_SERVICE_INTERNAL_PORT:-8000}"
    <<: *service-common

  vacancy-parser-worker:
    build:
      dockerfile: infra/docker/vacancy-parser/Dockerfile
      <<: *build-common
    <<: *service-common

  vacancy-parser-beat:
    build:
      dockerfile: infra/docker/vacancy-parser/Dockerfile
      <<: *build-common
    <<: *service-common

  vacancy-parser-migrator:
    build:
      dockerfile: infra/docker/vacancy-parser/Dockerfile
      <<: *build-common
    <<: *service-common

  vacancy-processor:
    build:
      dockerfile: infra/docker/vacancy-processor/Dockerfile
      <<: *build-common
    ports:
      - "${VACANCY_PROCESSOR_PORT:-8004}:${ENV_SERVICE_INTERNAL_PORT:-8000}"
    <<: *service-common

  vacancy-processor-worker:
    build:
      dockerfile: infra/docker/vacancy-processor/Dockerfile
      <<: *build-common
    <<: *service-common

  vacancy-processor-beat:
    build:
      dockerfile: infra/docker/vacancy-processor/Dockerfile
      <<: *build-common
    <<: *service-common

  vacancy-processor-migrator:
    build:
      dockerfile: infra/docker/vacancy-processor/Dockerfile
      <<: *build-common
    <<: *service-common

  vacancy-matcher:
    build:
      dockerfile: infra/docker/vacancy-matcher/Dockerfile
      <<: *build-common
    ports:
      - "${VACANCY_MATCHER_PORT:-8006}:${ENV_SERVICE_INTERNAL_PORT:-8000}"
    <<: *service-common

  telegram-bot:
    build:
      dockerfile: infra/docker/telegram-bot/Dockerfile
      <<: *build-common
    ports:
      - "${TELEGRAM_BOT_PORT:-8005}:${ENV_SERVICE_INTERNAL_PORT:-8000}"
    healthcheck:
      test: [ "CMD", "true" ] # supress because webhook may be disabled
    <<: *service-common

  telegram-bot-worker:
    build:
      dockerfile: infra/docker/telegram-bot/Dockerfile
      <<: *build-common
    <<: *service-common

  telegram-bot-migrator:
    build:
      dockerfile: infra/docker/telegram-bot/Dockerfile
      <<: *build-common
    <<: *service-common
