"""added models

Revision ID: 4972ee8abcd8
Revises: b040edb2dcb1
Create Date: 2025-09-30 15:41:05.889482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4972ee8abcd8'
down_revision: Union[str, Sequence[str], None] = 'b040edb2dcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('link'),
    schema='vacancy_parser'
    )
    op.create_index('idx_vacancies_fingerprint_trgm', 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_using='gist', postgresql_ops={'fingerprint': 'gist_trgm_ops'})
    op.create_index('idx_vacancies_hash_not_processed', 'vacancies', ['hash'], unique=False, schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    op.create_index('idx_vacancies_not_processed', 'vacancies', ['processed_at'], unique=False, schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    op.create_index('idx_vacancies_published_at_desc', 'vacancies', [sa.literal_column('published_at DESC')], unique=False, schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_vacancies_published_at'), 'vacancies', ['published_at'], unique=False, schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_vacancies_source'), 'vacancies', ['source'], unique=False, schema='vacancy_parser')
    op.create_table('habr_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vacancy_parser.vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vacancy_parser'
    )
    op.create_table('head_hunter_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vacancy_parser.vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vacancy_parser'
    )
    op.create_table('telegram_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_username', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vacancy_parser.vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vacancy_parser'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_vacancies', schema='vacancy_parser')
    op.drop_table('head_hunter_vacancies', schema='vacancy_parser')
    op.drop_table('habr_vacancies', schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_vacancies_source'), table_name='vacancies', schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_vacancies_published_at'), table_name='vacancies', schema='vacancy_parser')
    op.drop_index('idx_vacancies_published_at_desc', table_name='vacancies', schema='vacancy_parser')
    op.drop_index('idx_vacancies_not_processed', table_name='vacancies', schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    op.drop_index('idx_vacancies_hash_not_processed', table_name='vacancies', schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    op.drop_index('idx_vacancies_fingerprint_trgm', table_name='vacancies', schema='vacancy_parser', postgresql_using='gist', postgresql_ops={'fingerprint': 'gist_trgm_ops'})
    op.drop_table('vacancies', schema='vacancy_parser')
    # ### end Alembic commands ###
