"""added fingerprint unique and indexes

Revision ID: 7addd36ada1a
Revises: 369901a5e043
Create Date: 2025-10-14 15:32:02.316792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7addd36ada1a'
down_revision: Union[str, Sequence[str], None] = '369901a5e043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
       DELETE FROM vacancy_parser.vacancies v
           USING (
               SELECT id, fingerprint,
                      ROW_NUMBER() OVER (PARTITION BY fingerprint ORDER BY published_at DESC) as rn
               FROM vacancy_parser.vacancies
           ) t
       WHERE v.id = t.id AND t.rn > 1;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vacancies_hash_key'), 'vacancies', schema='vacancy_parser', type_='unique')
    op.create_index(op.f('ix_vacancy_parser_vacancies_fingerprint'), 'vacancies', ['fingerprint'], unique=True, schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_vacancies_hash'), 'vacancies', ['hash'], unique=True, schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_parser_vacancies_hash'), table_name='vacancies', schema='vacancy_parser')
    op.drop_index(op.f('ix_vacancy_parser_vacancies_fingerprint'), table_name='vacancies', schema='vacancy_parser')
    op.create_unique_constraint(op.f('vacancies_hash_key'), 'vacancies', ['hash'], schema='vacancy_parser', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
