"""added vacancy cascade delete

Revision ID: 369901a5e043
Revises: 4972ee8abcd8
Create Date: 2025-10-14 15:28:45.477989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369901a5e043'
down_revision: Union[str, Sequence[str], None] = '4972ee8abcd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('habr_vacancies_id_fkey'), 'habr_vacancies', schema='vacancy_parser', type_='foreignkey')
    op.create_foreign_key("habr_vacancies_id_fkey", 'habr_vacancies', 'vacancies', ['id'], ['id'], source_schema='vacancy_parser', referent_schema='vacancy_parser', ondelete='CASCADE')
    op.drop_constraint(op.f('head_hunter_vacancies_id_fkey'), 'head_hunter_vacancies', schema='vacancy_parser', type_='foreignkey')
    op.create_foreign_key("head_hunter_vacancies_id_fkey", 'head_hunter_vacancies', 'vacancies', ['id'], ['id'], source_schema='vacancy_parser', referent_schema='vacancy_parser', ondelete='CASCADE')
    op.drop_constraint(op.f('telegram_vacancies_id_fkey'), 'telegram_vacancies', schema='vacancy_parser', type_='foreignkey')
    op.create_foreign_key("telegram_vacancies_id_fkey", 'telegram_vacancies', 'vacancies', ['id'], ['id'], source_schema='vacancy_parser', referent_schema='vacancy_parser', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("telegram_vacancies_id_fkey", 'telegram_vacancies', schema='vacancy_parser', type_='foreignkey')
    op.create_foreign_key(op.f('telegram_vacancies_id_fkey'), 'telegram_vacancies', 'vacancies', ['id'], ['id'], source_schema='vacancy_parser', referent_schema='vacancy_parser')
    op.drop_constraint("head_hunter_vacancies_id_fkey", 'head_hunter_vacancies', schema='vacancy_parser', type_='foreignkey')
    op.create_foreign_key(op.f('head_hunter_vacancies_id_fkey'), 'head_hunter_vacancies', 'vacancies', ['id'], ['id'], source_schema='vacancy_parser', referent_schema='vacancy_parser')
    op.drop_constraint("habr_vacancies_id_fkey", 'habr_vacancies', schema='vacancy_parser', type_='foreignkey')
    op.create_foreign_key(op.f('habr_vacancies_id_fkey'), 'habr_vacancies', 'vacancies', ['id'], ['id'], source_schema='vacancy_parser', referent_schema='vacancy_parser')
    # ### end Alembic commands ###
