"""added fingerprint index

Revision ID: 89b4a4ad11bf
Revises: bc38d18f4fb2
Create Date: 2025-09-30 13:44:27.325664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b4a4ad11bf'
down_revision: Union[str, Sequence[str], None] = 'bc38d18f4fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vacancies_fingerprint_trgm', 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_using='gin', postgresql_ops={'fingerprint': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_fingerprint_trgm', table_name='vacancies', schema='vacancy_parser', postgresql_using='gin', postgresql_ops={'fingerprint': 'gin_trgm_ops'})
    # ### end Alembic commands ###
