"""changed gin to gist index

Revision ID: 13197d508098
Revises: 488e97a03781
Create Date: 2025-09-30 15:24:25.840825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13197d508098'
down_revision: Union[str, Sequence[str], None] = '488e97a03781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_vacancies_fingerprint_similarity'), table_name='vacancies', schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_vacancies_fingerprint_trgm'), table_name='vacancies', schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_vacancy_parser_vacancies_hash'), table_name='vacancies', schema='vacancy_parser')
    op.create_unique_constraint('idx_vacancies_hash', 'vacancies', ['hash'], schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_vacancies_hash', 'vacancies', schema='vacancy_parser', type_='unique')
    op.create_index(op.f('ix_vacancy_parser_vacancies_hash'), 'vacancies', ['hash'], unique=True, schema='vacancy_parser')
    op.create_index(op.f('idx_vacancies_fingerprint_trgm'), 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_vacancies_fingerprint_similarity'), 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
