"""added fingerprint index

Revision ID: 5869c8112d45
Revises: d8e22d4eae19
Create Date: 2025-09-28 17:07:02.195048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5869c8112d45'
down_revision: Union[str, Sequence[str], None] = 'd8e22d4eae19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vacancies_fingerprint_trgm', 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_using='gin', postgresql_ops={'fingerprint': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_fingerprint_trgm', table_name='vacancies', schema='vacancy_parser', postgresql_using='gin', postgresql_ops={'fingerprint': 'gin_trgm_ops'})
    # ### end Alembic commands ###
