"""added index hash is_processed

Revision ID: 8359064a8375
Revises: 13197d508098
Create Date: 2025-09-30 15:27:59.918857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8359064a8375'
down_revision: Union[str, Sequence[str], None] = '13197d508098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vacancies_hash_not_processed', 'vacancies', ['hash'], unique=False, schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_hash_not_processed', table_name='vacancies', schema='vacancy_parser', postgresql_where='processed_at IS NULL')
    # ### end Alembic commands ###
