"""added gist index

Revision ID: 710a97d1bf32
Revises: 48e5cdacf8d5
Create Date: 2025-12-07 20:28:34.605024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710a97d1bf32'
down_revision: Union[str, Sequence[str], None] = '48e5cdacf8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_vacancies_fingerprint_trgm'), table_name='vacancies', schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_vacancies_fingerprint_gist', 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_using='gist', postgresql_ops={'fingerprint': 'gist_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_fingerprint_gist', table_name='vacancies', schema='vacancy_parser', postgresql_using='gist', postgresql_ops={'fingerprint': 'gist_trgm_ops'})
    op.create_index(op.f('idx_vacancies_fingerprint_trgm'), 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
