"""fix gist to gin index

Revision ID: 48e5cdacf8d5
Revises: 7addd36ada1a
Create Date: 2025-10-14 15:50:03.051619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e5cdacf8d5'
down_revision: Union[str, Sequence[str], None] = '7addd36ada1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vacancies_fingerprint_trgm', 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_using='gin', postgresql_ops={'fingerprint': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_fingerprint_trgm', table_name='vacancies', schema='vacancy_parser', postgresql_using='gin', postgresql_ops={'fingerprint': 'gin_trgm_ops'})
    # ### end Alembic commands ###
