"""changed published desc index

Revision ID: 816a6e9358b7
Revises: 89b4a4ad11bf
Create Date: 2025-09-30 13:53:54.712410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816a6e9358b7'
down_revision: Union[str, Sequence[str], None] = '89b4a4ad11bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_parser_vacancies_processed_at'), table_name='vacancies', schema='vacancy_parser')
    op.create_index('idx_vacancies_published_at_desc', 'vacancies', [sa.literal_column('published_at DESC')], unique=False, schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_published_at_desc', table_name='vacancies', schema='vacancy_parser')
    op.create_index(op.f('ix_vacancy_parser_vacancies_processed_at'), 'vacancies', ['processed_at'], unique=False, schema='vacancy_parser')
    # ### end Alembic commands ###
