"""added hash index

Revision ID: 488e97a03781
Revises: 816a6e9358b7
Create Date: 2025-09-30 14:50:31.611924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488e97a03781'
down_revision: Union[str, Sequence[str], None] = '816a6e9358b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vacancies_hash_key'), 'vacancies', schema='vacancy_parser', type_='unique')
    op.create_index(op.f('ix_vacancy_parser_vacancies_hash'), 'vacancies', ['hash'], unique=True, schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_parser_vacancies_hash'), table_name='vacancies', schema='vacancy_parser')
    op.create_unique_constraint(op.f('vacancies_hash_key'), 'vacancies', ['hash'], schema='vacancy_parser', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
