"""removed fingerprint index

Revision ID: 1b5decc10f94
Revises: 5869c8112d45
Create Date: 2025-09-28 20:09:29.741794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5decc10f94'
down_revision: Union[str, Sequence[str], None] = '5869c8112d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_vacancies_fingerprint_trgm'), table_name='vacancies', schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vacancies_fingerprint_trgm'), 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_ops={'fingerprint': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
