"""added habr vacancy

Revision ID: d8e22d4eae19
Revises: a6a3981b800a
Create Date: 2025-09-23 12:26:56.648832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e22d4eae19'
down_revision: Union[str, Sequence[str], None] = 'a6a3981b800a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habr_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['vacancy_parser.vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='vacancy_parser'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habr_vacancies', schema='vacancy_parser')
    # ### end Alembic commands ###
