"""added fingerprint index new

Revision ID: 01bbfb3db633
Revises: 8359064a8375
Create Date: 2025-09-30 15:29:48.794645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bbfb3db633'
down_revision: Union[str, Sequence[str], None] = '8359064a8375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vacancies_fingerprint_trgm', 'vacancies', ['fingerprint'], unique=False, schema='vacancy_parser', postgresql_using='gist', postgresql_ops={'fingerprint': 'gist_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancies_fingerprint_trgm', table_name='vacancies', schema='vacancy_parser', postgresql_using='gist', postgresql_ops={'fingerprint': 'gist_trgm_ops'})
    # ### end Alembic commands ###
