"""removed telegram message id

Revision ID: bc38d18f4fb2
Revises: 1b5decc10f94
Create Date: 2025-09-29 18:02:35.999455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc38d18f4fb2'
down_revision: Union[str, Sequence[str], None] = '1b5decc10f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_vacancies', 'message_id', schema='vacancy_parser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_vacancies', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='vacancy_parser')
    # ### end Alembic commands ###
