"""added indexes

Revision ID: f575dc5e2e33
Revises: 943ca8ad0139
Create Date: 2025-10-01 22:40:22.802488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f575dc5e2e33'
down_revision: Union[str, Sequence[str], None] = '943ca8ad0139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_processor_vacancy_published_at'), table_name='vacancies', schema='vacancy_processor')
    op.drop_index(op.f('ix_vacancy_processor_vacancy_source'), table_name='vacancies', schema='vacancy_processor')
    op.create_index('idx_vacancy_profession_id', 'vacancies', ['profession_id'], unique=False, schema='vacancy_processor')
    op.create_index('idx_vacancy_source_published_at', 'vacancies', ['source', 'published_at'], unique=False, schema='vacancy_processor')
    op.create_index(op.f('ix_vacancy_processor_vacancies_published_at'), 'vacancies', ['published_at'], unique=False, schema='vacancy_processor')
    op.create_index(op.f('ix_vacancy_processor_vacancies_source'), 'vacancies', ['source'], unique=False, schema='vacancy_processor')
    op.create_index('idx_vacancy_grades_grade_id_vacancy_id', 'vacancy_grades', ['grade_id', 'vacancy_id'], unique=False, schema='vacancy_processor')
    op.create_index('idx_vacancy_skills_skill_id_vacancy_id', 'vacancy_skills', ['skill_id', 'vacancy_id'], unique=False, schema='vacancy_processor')
    op.create_index('idx_vacancy_work_formats_work_format_id_vacancy_id', 'vacancy_work_formats', ['work_format_id', 'vacancy_id'], unique=False, schema='vacancy_processor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vacancy_work_formats_work_format_id_vacancy_id', table_name='vacancy_work_formats', schema='vacancy_processor')
    op.drop_index('idx_vacancy_skills_skill_id_vacancy_id', table_name='vacancy_skills', schema='vacancy_processor')
    op.drop_index('idx_vacancy_grades_grade_id_vacancy_id', table_name='vacancy_grades', schema='vacancy_processor')
    op.drop_index(op.f('ix_vacancy_processor_vacancies_source'), table_name='vacancies', schema='vacancy_processor')
    op.drop_index(op.f('ix_vacancy_processor_vacancies_published_at'), table_name='vacancies', schema='vacancy_processor')
    op.drop_index('idx_vacancy_source_published_at', table_name='vacancies', schema='vacancy_processor')
    op.drop_index('idx_vacancy_profession_id', table_name='vacancies', schema='vacancy_processor')
    op.create_index(op.f('ix_vacancy_processor_vacancy_source'), 'vacancies', ['source'], unique=False, schema='vacancy_processor')
    op.create_index(op.f('ix_vacancy_processor_vacancy_published_at'), 'vacancies', ['published_at'], unique=False, schema='vacancy_processor')
    # ### end Alembic commands ###
