services:
  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    container_name: pgbouncer
    env_file: ${SERVICE_PROJECT_ROOT:-../../..}/infra/.env
    environment:
      - DB_HOST=${POSTGRES_HOST:-postgres}
      - DB_NAME=${POSTGRES_DB:-syncit}
      - DB_USER=${POSTGRES_USER:-syncit}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${POSTGRES_PORT:-5432}
      - LISTEN_PORT=${PGBOUNCER_PORT:-6432}

      - MAX_CLIENT_CONN=${PGBOUNCER_MAX_CLIENT_CONN:-1000}
      - POOL_MODE=transaction
      - AUTH_TYPE=scram-sha-256
    ports:
      - "${PGBOUNCER_PORT:-6432}:${PGBOUNCER_PORT:-6432}"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "${PGBOUNCER_HOST:-pgbouncer}", "-p", "${PGBOUNCER_PORT:-6432}", "-d", "${PGBOUNCER_DB:-syncit}", "-U", "${PGBOUNCER_USER:-syncit}"]
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 1s
      start_interval: 1s
