# $schema: https://json.schemastore.org/github-workflow.json

name: Deploying

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10
    concurrency:
      group: deploy-prod
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.sh,infra/docker,Makefile"
          target: "/srv/${{ vars.PROJECT_NAME }}"

      - name: Run deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 8m
          script: |
            chmod +x /srv/${{ vars.PROJECT_NAME }}/deploy.sh
            /srv/${{ vars.PROJECT_NAME }}/deploy.sh
