# $schema: https://json.schemastore.org/github-workflow.json

name: Linting

on:
  workflow_call:

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv and python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13.4"
          enable-cache: true

      - name: Install dependencies
        run: make venv-local

      - name: Cache mypy
        uses: actions/cache@v5
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-${{ hashFiles('uv.lock') }}-${{ hashFiles('pyproject.toml') }}

      - name: Check Linting and Formating
        run: make lint

      - name: Send Telegram Notification
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Linting
          title: ❌ Lint Failure ❌
          to: ${{ secrets.TELEGRAM_NOTIFIER_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFIER_BOT_TOKEN }}
